lib/BasicGenerator.js
上个 pr 不小心把向 package.json 传递参数的修改 discard 了。。
=> fix: forward params to package.json

templates/block/_gitignore, templates/block/package.json
fix name in package.json and add some gitignore.
=> fix block tempalte

lib/generators/ant-design-pro/index.js
=> fix: yarn create umi - ant-design-pro时报错

lib/generators/app/templates/package.json, lib/generators/app/templates/src/layouts/index.tsx
fix https://github.com/umijs/create-umi/pull/47#discussion_r265413018
=> chore: remove BasicLayoutProps in template

.gitignore, lib/generators/ant-design-pro/.babelrc, lib/generators/ant-design-pro/README.md, lib/generators/ant-design-pro/filterPkg.js, lib/generators/ant-design-pro/index.js, package.json
使用 pro 的项目中 package.json 生成项目的 package.json.
解耦pro的文件
=> don't copy pro files

lib/generators/ant-design-pro/index.js, package.json
Update with [Sylvanas](https://github.com/umijs/sylvanas).
=> refactor: use sylvanas to convert ts

package.json
=> fix: lock inquirer

lib/generators/app/templates/package.json, lib/generators/block/templates/package.json
=> dep: upgrade umi-types to 0.3

.travis.yml, lib/BasicGenerator.js, lib/generators/ant-design-pro/index.js, lib/run.js, package.json, test/fixtures/mock_cnpmjs.js, test/fixtures/mock_github.js, test/index.test.js
=> test: 添加集成测试

lib/generators/app/templates/package.json, lib/generators/app/templates/src/app.ts, lib/generators/app/templates/src/global.css, lib/generators/app/templates/src/pages/index.js, lib/generators/app/templates/src/pages/index.tsx, lib/generators/block/templates/package.json, lib/generators/library/templates/package.json, lib/generators/plugin/templates/package.json
=> trims following newline

lib/generators/app/templates/tslint.yml
Close https://github.com/umijs/umi/issues/3342
=> fix: run `yarn lint:ts` error

lib/generators/ant-design-pro/index.js, test/index.test.js
`tsconfig.json` should not be generated while `JavaScript` is picked.
Close https://github.com/umijs/umi/issues/3273
=> fix: remove unexpected tsconfig.json from JavaScript creation

lib/generators/plugin/templates/package.json
修复 UI plugin react 未 external bug
=> fix: ui plugin react deps should peerDeps

lib/generators/app/templates/.umirc.js, lib/generators/app/templates/.umirc.ts
=> fix: app template routes use configuration

lib/generators/ant-design-pro/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/mock_cnpmjs.js, test/index.test.js
支持选择pro的antd@4 版本。并且支持了码云下载
close https://github.com/ant-design/ant-design-pro/issues/5745
=> feat: support select antd@4

lib/generators/ant-design-pro/index.js, test/__snapshots__/index.test.js.snap
=> 💥 feat: antd@4 officially released

lib/generators/ant-design-pro/index.js, test/__snapshots__/index.test.js.snap, test/index.test.js
很用用户有 fetch:all-blocks 的需求
在新建项目的时候提供了下载全部的功能
=> ✨ features: support insert all blocks

package.json
close https://github.com/ant-design/ant-design-pro/issues/6250
=> 📌 versions: up sylvanas

test/index.test.js
ref https://github.com/ant-design/ant-design-pro/issues/6250
=> ✅ tests:add all blocs to js test

lib/generators/plugin/templates/package.json
https://github.com/umijs/create-umi/pull/97
=> fix: windows 用户无法运行项目

lib/generators/ant-design-pro/index.js, package.json, test/__snapshots__/index.test.js.snap, test/index.test.js
close https://github.com/ant-design/ant-design-pro/issues/6363
=> 🐛 bug: Add the judgment that the folder is not empty

cli.js, lib/generators/ant-design-pro/index.js, lib/run.js, test/__snapshots__/index.test.js.snap, test/index.test.js
Reverts umijs/create-umi#106
close https://github.com/ant-design/ant-design-pro/issues/6504
=> Revert "💥 feat: support umi@3 app"

lib/generators/ant-design-pro/index.js
close https://github.com/ant-design/ant-design-pro/issues/6537
=> fix: do not overwrite version

package.json
close https://github.com/ant-design/ant-design-pro/issues/7247
close https://github.com/ant-design/ant-design-pro/issues/7223
close https://github.com/ant-design/ant-design-pro/issues/7177
=> up sylvanas to v5

lib/generators/plugin/templates/package.json
one more comma in plugin templates package.json
=> fix:  one more comma
